# Generated by Django 4.2.6 on 2025-06-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.AddField(
            model_name='placementdata',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
