# Generated by Django 4.2.6 on 2025-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_placementdata_student_is_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondata',
            name='department_field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='image_field',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='name_field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='prn_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
