# Generated by Django 4.2.6 on 2025-06-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_commondata_department_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
