# Generated by Django 4.2.6 on 2025-06-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_placementdata_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
