# Generated by Django 4.2.6 on 2025-06-13 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_college_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondata',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='commondata',
            name='header',
        ),
        migrations.AddField(
            model_name='commondata',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='department_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='name_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='start_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
