# Generated by Django 4.2.6 on 2025-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_commondata_footer_remove_commondata_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField(null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commondata',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='commondata',
            name='start_year',
        ),
    ]
