# Generated by Django 4.2.6 on 2025-06-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_year_remove_commondata_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='start_year',
            field=models.DateField(null=True, unique=True),
        ),
    ]
